export const GET_WORKOUT_DATA = "GET_WORKOUT_DATA";
export const DELETE_WORKOUT_BY_ID = "DELETE_WORKOUT_BY_ID";
export const ADD_NEW_WORKOUT = "ADD_NEW_WORKOUT";
export const EDIT_WORKOUTS = "EDIT_WORKOUTS";